import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import Sidebar from '../ui/Sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Discord | Amigos',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <div className={`${inter.className} flex min-h-screen bg-black text-white`}>
      <Sidebar />
      <main className="bg-slate-700 flex-1">{children}</main>
    </div>
  )
}
