import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Sidebar from './components/Sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Discord Clone',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex min-h-screen bg-black text-white`}>
        <Sidebar />
        <section className="basis-[270px]">{children}</section>

        <main className="bg-slate-700 flex-1"></main>

        <section className="basis-[200px] bg-gray-500"></section>
      </body>
    </html>
  )
}
